### ISSUE TITLE
Different results between 0.9.66 and 0.11.0

### ISSUE THREAD

**Issue by davidhealey** [GrandOrgue/LoopAuditioneer#9]
I've loaded the same sample into both versions and set the search settings to the same values. In 0.9.66 a loop is returned, but in 0.11.0 it tells me no loops are found. Has the algorithm changed significantly between the two versions or is there some other setting perhaps that I'm missing?

Additionally audio playback works in 0.9.66 but doesn't in 0.11.0.

I'm on Debian Testing, using the AppImage.

Thanks.

**Comment by larspalo** [comment]
There are some changes. Among other things the comparison "window" is positioned slightly differently, loop search prioritizes finding loops later in the sustain section and the quality checking of a loop now takes all channels into account. I'd believe that the last one can be the main cause that you might need to "relax" the quality comparison settings in order to find any loops.

The AppImage doesn't support using jack, only ALSA and pulse. Using the tar.gz package run in place should support jack though. In the File->Audio Settings you should see available options but I know that it needs some work to avoid certain issues...

**Comment by davidhealey** [comment]
Thanks, I'll try adjusting the settings

**Comment by davidhealey** [comment]
After some experimenting I'm finding that I have to bump up the settings quite a bit to find loops in some samples that the previous version would easily find lots of loops in. However the quality of the loops (the seamlessness) seems to be much better in the newer version, so I think this is an improvement overall.
